### ISSUE TITLE
Make the page either hug the left or center

### ISSUE THREAD

**Issue by jonyo** [nkcmr/cfm-promise-zones#11]
It hugs the right side at the moment, which ends up with the visualizations get cut off on certain window sizes.  Change it so the visualizations do not get cut off, either hug the left side or center, whichever looks better and makes sure the visualizations don't get cut off.

**Comment by dksmith01** [comment]
Fixed it by widening the viewable area from 800px to 1084 (1024 + 30 padding on each side)
